# Campos obrigatórios (Modelos do evaluation)
run_id: "my_run"
backend: "vllm"
model_paths:
  - path: "Qwen/Qwen2.5-3B-Instruct"
    custom: false
    tokenizer_path: "Qwen/Qwen2.5-3B-Instruct"
  - path: "Qwen/Qwen3-4B"
    custom: false
    tokenizer_path: "Qwen/Qwen3-4B"
  - path: "meta-llama/Llama-3.2-3B-Instruct"
    custom: false
    tokenizer_path: "meta-llama/Llama-3.2-3B-Instruct"

# Campos opcionais (Parâmetros do script)
multi_gpu:
  enabled: false
  num_gpus: 1

run_local: true
flash_attention: false
update_leaderboard: true
num_shots: 5
num_experiments: 3
benchmark_names:
  - "assin2rte"
  - "assin2sts"
  - "bluex"
  - "enem"
  - "hatebr"
  - "portuguese_hate_speech"
  - "faquad"
  - "tweetsentbr"
  - "oab"
  - "poscomp"
  - "energy_regulacao"
